# Smallworld development stack
# Usage:
#   make up       — start all services (API, MCP, Web) in background
#   make down     — stop all services
#   make status   — show which services are running
#   make logs     — tail all log files
#   make restart  — down + up

API_PORT ?= 4180
MCP_PORT ?= 4181
WEB_PORT ?= 4182

LOGDIR := $(CURDIR)/.logs
API_LOG := $(LOGDIR)/api.log
MCP_LOG := $(LOGDIR)/mcp.log
WEB_LOG := $(LOGDIR)/web.log
TOOL_LOG := $(LOGDIR)/tool-calls.ndjson
API_PID := $(LOGDIR)/api.pid
MCP_PID := $(LOGDIR)/mcp.pid
WEB_PID := $(LOGDIR)/web.pid

.PHONY: up down status logs restart up-api up-mcp up-web down-api down-mcp down-web gen-env help

up: gen-env | $(LOGDIR)
	@$(MAKE) --no-print-directory up-api up-mcp up-web
	@echo ""
	@$(MAKE) --no-print-directory status

$(LOGDIR):
	@mkdir -p $(LOGDIR)

gen-env:
	@echo "# Auto-generated by Makefile — edit port vars there instead" > apps/web/.env.local
	@echo "NEXT_PUBLIC_API_BASE_URL=http://localhost:$(API_PORT)" >> apps/web/.env.local
	@echo "MCP_SERVER_URL=http://127.0.0.1:$(MCP_PORT)/mcp" >> apps/web/.env.local
	@# Forward secrets from root .env into the web app
	@grep -E '^(DEEPSEEK_|ANTHROPIC_|CESIUM_|MAPBOX_)' .env >> apps/web/.env.local 2>/dev/null || true
	@# Forward Google Maps API key (for Photorealistic 3D Tiles) — browser needs NEXT_PUBLIC_ prefix
	@grep -E '^GOOGLE_MAPS_API_KEY=' .env 2>/dev/null | sed 's/^GOOGLE_MAPS_API_KEY=/NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=/' >> apps/web/.env.local || true
	@# Forward Cesium Ion token (for Ion terrain + imagery) — browser needs NEXT_PUBLIC_ prefix
	@grep -E '^CESIUM_ION_TOKEN=' .env 2>/dev/null | sed 's/^CESIUM_ION_TOKEN=/NEXT_PUBLIC_CESIUM_ION_TOKEN=/' >> apps/web/.env.local || true

up-api:
	@if [ -f $(API_PID) ] && kill -0 $$(cat $(API_PID)) 2>/dev/null; then \
		echo "API already running (pid $$(cat $(API_PID)))"; \
	else \
		echo "Starting API on :$(API_PORT)..."; \
		cd apps/api && \
			CORS_ORIGINS='http://localhost:$(WEB_PORT),http://127.0.0.1:$(WEB_PORT)' \
			PREVIEW_RENDERER_BASE_URL=http://127.0.0.1:$(WEB_PORT)/render/preview \
			nohup uv run uvicorn smallworld_api.main:app --reload --host 0.0.0.0 --port $(API_PORT) \
			> $(API_LOG) 2>&1 & echo $$! > $(API_PID); \
		sleep 1; \
		echo "API started (pid $$(cat $(API_PID)))"; \
	fi

up-mcp:
	@if [ -f $(MCP_PID) ] && kill -0 $$(cat $(MCP_PID)) 2>/dev/null; then \
		echo "MCP already running (pid $$(cat $(MCP_PID)))"; \
	else \
		echo "Starting MCP on :$(MCP_PORT)..."; \
		cd apps/api && MCP_HTTP_PORT=$(MCP_PORT) nohup uv run python -m smallworld_api.mcp.cli --transport http \
			> $(MCP_LOG) 2>&1 & echo $$! > $(MCP_PID); \
		sleep 1; \
		echo "MCP started (pid $$(cat $(MCP_PID)))"; \
	fi

up-web:
	@if [ -f $(WEB_PID) ] && kill -0 $$(cat $(WEB_PID)) 2>/dev/null; then \
		echo "Web already running (pid $$(cat $(WEB_PID)))"; \
	else \
		echo "Starting Web on :$(WEB_PORT)..."; \
		cd apps/web && nohup pnpm exec next dev --port $(WEB_PORT) > $(WEB_LOG) 2>&1 & echo $$! > $(WEB_PID); \
		sleep 2; \
		echo "Web started (pid $$(cat $(WEB_PID)))"; \
	fi

down: down-web down-mcp down-api
	@echo "All services stopped"

down-api:
	@if [ -f $(API_PID) ]; then \
		PID=$$(cat $(API_PID)); \
		if kill -0 $$PID 2>/dev/null; then \
			echo "Stopping API (pid $$PID)..."; \
			kill $$PID 2>/dev/null; \
			sleep 1; \
			kill -0 $$PID 2>/dev/null && kill -9 $$PID 2>/dev/null; \
		fi; \
		rm -f $(API_PID); \
	fi
	@# Also kill any orphaned uvicorn on the API port
	@lsof -ti :$(API_PORT) 2>/dev/null | xargs kill 2>/dev/null || true

down-mcp:
	@if [ -f $(MCP_PID) ]; then \
		PID=$$(cat $(MCP_PID)); \
		if kill -0 $$PID 2>/dev/null; then \
			echo "Stopping MCP (pid $$PID)..."; \
			kill $$PID 2>/dev/null; \
			sleep 1; \
			kill -0 $$PID 2>/dev/null && kill -9 $$PID 2>/dev/null; \
		fi; \
		rm -f $(MCP_PID); \
	fi
	@lsof -ti :$(MCP_PORT) 2>/dev/null | xargs kill 2>/dev/null || true

down-web:
	@if [ -f $(WEB_PID) ]; then \
		PID=$$(cat $(WEB_PID)); \
		if kill -0 $$PID 2>/dev/null; then \
			echo "Stopping Web (pid $$PID)..."; \
			kill $$PID 2>/dev/null; \
			sleep 1; \
			kill -0 $$PID 2>/dev/null && kill -9 $$PID 2>/dev/null; \
		fi; \
		rm -f $(WEB_PID); \
	fi
	@lsof -ti :$(WEB_PORT) 2>/dev/null | xargs kill 2>/dev/null || true

status:
	@echo "=== Smallworld Stack ==="
	@printf "  API  (:$(API_PORT))  "; \
	if [ -f $(API_PID) ] && kill -0 $$(cat $(API_PID)) 2>/dev/null; then \
		echo "UP  (pid $$(cat $(API_PID)))"; \
	elif lsof -ti :$(API_PORT) >/dev/null 2>&1; then \
		echo "UP  (port in use, no pidfile)"; \
	else \
		echo "DOWN"; \
	fi
	@printf "  MCP  (:$(MCP_PORT))  "; \
	if [ -f $(MCP_PID) ] && kill -0 $$(cat $(MCP_PID)) 2>/dev/null; then \
		echo "UP  (pid $$(cat $(MCP_PID)))"; \
	elif lsof -ti :$(MCP_PORT) >/dev/null 2>&1; then \
		echo "UP  (port in use, no pidfile)"; \
	else \
		echo "DOWN"; \
	fi
	@printf "  Web  (:$(WEB_PORT))  "; \
	if [ -f $(WEB_PID) ] && kill -0 $$(cat $(WEB_PID)) 2>/dev/null; then \
		echo "UP  (pid $$(cat $(WEB_PID)))"; \
	elif lsof -ti :$(WEB_PORT) >/dev/null 2>&1; then \
		echo "UP  (port in use, no pidfile)"; \
	else \
		echo "DOWN"; \
	fi
	@echo ""
	@echo "URLs:"
	@echo "  API  http://localhost:$(API_PORT)"
	@echo "  MCP  http://localhost:$(MCP_PORT)/mcp"
	@echo "  Web  http://localhost:$(WEB_PORT)"

logs:
	@tail -f $(API_LOG) $(MCP_LOG) $(WEB_LOG) $(TOOL_LOG) 2>/dev/null || echo "No log files found. Run 'make up' first."

restart: down up

help:
	@echo "Smallworld development stack"
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "  up          Start all services (API, MCP, Web) in background"
	@echo "  down        Stop all services"
	@echo "  restart     Stop and restart all services"
	@echo "  status      Show which services are running"
	@echo "  logs        Tail all log files"
	@echo ""
	@echo "  up-api      Start API only (:$(API_PORT))"
	@echo "  up-mcp      Start MCP only (:$(MCP_PORT))"
	@echo "  up-web      Start Web only (:$(WEB_PORT))"
	@echo "  down-api    Stop API"
	@echo "  down-mcp    Stop MCP"
	@echo "  down-web    Stop Web"
	@echo "  gen-env     Regenerate apps/web/.env.local from port vars"
	@echo ""
	@echo "  help        Show this help"
